const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{randomUUID}=require('node:crypto');
async function setup(t,email){const {PGlite}=await import('@electric-sql/pglite'),{createPGlitePool}=await import('./pglite-pool.mjs'),{RegistrationService}=await import('../server/registration-service.mjs');const db=new PGlite();t.after(()=>db.close());for(const name of fs.readdirSync(path.join(__dirname,'../netlify/database/migrations')).filter(f=>f.endsWith('.sql')).sort())await db.exec(fs.readFileSync(path.join(__dirname,'../netlify/database/migrations',name),'utf8'));const pool=createPGlitePool(db),service=new RegistrationService(pool,email),cup=service.teamCup,tid=(await cup.create()).id;return {pool,service,cup,tid,view:()=>cup.view(tid,true)};}
const input=(tid,n)=>({tournamentId:tid,teamName:`Correction Team ${n}`,requestKey:randomUUID(),consent:true,members:[1,2,3,4].map(i=>({name:`Team ${n} Player ${i}`,email:`c${n}p${i}@example.test`,phone:'07123456789',category:i<3?'men':'women',shirtSize:'M'}))});
const user={id:'owner',email:'owner@example.test',roles:['admin']},override={override:true,reason:'Correct tournament data after organizer review'};
const fakeEmail={send:async()=>({messageId:'test-only'})};
test('18 configured team slots, team 19 waitlist toggle and audited capacity override',async t=>{
  const {cup,tid,view,pool}=await setup(t,fakeEmail);let s=await view();assert.equal(s.config.capacity,18);
  // Fee zero avoids unrelated bank setup in a capacity-only test.
  s.config.fee_per_person=0;await cup.configure({tournamentId:tid,version:s.version,config:s.config},user);
  for(let n=1;n<=18;n++){const r=await cup.register(input(tid,n));assert.equal(r.team.status,'pending');await cup.teamStatus({tournamentId:tid,teamId:r.team.id,status:'confirmed',user});assert.equal((await view()).confirmed_count,n);}
  const extra=await cup.register(input(tid,19));assert.equal(extra.team.status,'waitlisted');await assert.rejects(cup.teamStatus({tournamentId:tid,teamId:extra.team.id,status:'confirmed',user}),/Capacity 18/);
  s=await view();s.config.auto_waitlist=false;await cup.configure({tournamentId:tid,version:s.version,config:s.config},user);await assert.rejects(cup.register(input(tid,20)),/automatic waitlist is disabled/);
  await cup.teamStatus({tournamentId:tid,teamId:extra.team.id,status:'confirmed',user,...override});assert.equal((await view()).confirmed_count,19);
  s=await view();s.config.capacity=24;await cup.configure({tournamentId:tid,version:s.version,config:s.config},user);assert.equal((await cup.register(input(tid,20))).team.status,'pending');
  assert.ok((await pool.query("select detail from score_events where action='team_status' and detail->>'reason' is not null")).rows.length);
});
test('Team Cup approval → captain payment instructions → receipt, failures persist and retry is idempotent',async t=>{
  const {createEmailService}=await import('../server/email.mjs');let fail=true;const attempts=[],logs=[];const email=createEmailService({env:{EMAIL_API_KEY:'fake-server-only-secret',EMAIL_FROM:'sender@example.test'},fetchImpl:async(url,options)=>{attempts.push(JSON.parse(options.body));return new Response(JSON.stringify(fail?{code:'invalid_parameter',message:'Sender email has not been verified.'}:{messageId:randomUUID()}),{status:fail?400:201});}});
  const {cup,tid,view,service,pool}=await setup(t,email);await service.payments.saveSettings({tournamentId:tid,revision:0,bank_account_name:'Dropshot Folks',bank_name:'Test Bank',sort_code:'12-34-56',account_number:'12345678',payment_reference_prefix:'DF',payment_instructions:'Use this reference.'});
  const team=(await cup.register(input(tid,1))).team,originalWarn=console.warn;console.warn=(...args)=>logs.push(args);let result;try{result=await cup.teamStatus({tournamentId:tid,teamId:team.id,status:'confirmed',user});}finally{console.warn=originalWarn;}
  assert.match(result.warning,/Sender email has not been verified/);let stored=(await view()).teams.find(t=>t.id===team.id);assert.equal(stored.status,'confirmed');assert.equal(stored.payment.payment_status,'pending');assert.equal(Number(stored.payment.payment_amount),88);assert.equal(stored.payment.payment_reference.length<=18,true);
  assert.equal(attempts.length,1);assert.equal(attempts[0].to[0].email,'c1p1@example.test');for(const value of ['Correction Team 1','Team 1 Player 4','£22.00','£88.00','Test Bank','123456','12345678','PAYMENT PENDING','2026','Westminster'])assert.ok(attempts[0].textContent.includes(value),value);
  assert.ok(!JSON.stringify(logs).includes('fake-server-only-secret'));assert.ok(!JSON.stringify(logs).includes('12345678'));assert.ok(logs[0][1].provider_http_status===400);
  fail=false;await cup.payments.action({tournamentId:tid,teamId:team.id,action:'retry',kind:'approval'},user,cup);await cup.payments.action({tournamentId:tid,teamId:team.id,action:'retry',kind:'approval'},user,cup);assert.equal(attempts.length,2);
  fail=true;result=await cup.payments.action({tournamentId:tid,teamId:team.id,action:'received'},user,cup);assert.match(result.warning,/Payment received/);stored=(await view()).teams.find(t=>t.id===team.id);const received=stored.payment.payment_received_at;assert.equal(stored.payment.payment_status,'paid');assert.ok(received);assert.equal(stored.payment.payment_received_by,user.email);
  fail=false;await cup.payments.action({tournamentId:tid,teamId:team.id,action:'retry',kind:'payment'},user,cup);await cup.payments.action({tournamentId:tid,teamId:team.id,action:'received'},user,cup);assert.equal(attempts.length,4);assert.match(attempts.at(-1).textContent,/Payment status: Paid/);assert.equal(new Date((await view()).teams[0].payment.payment_received_at).getTime(),new Date(received).getTime());
  let s=await view();s.config.email_members=true;await cup.configure({tournamentId:tid,version:s.version,config:s.config},user);const team2=(await cup.register(input(tid,2))).team;await cup.teamStatus({tournamentId:tid,teamId:team2.id,status:'confirmed',user});assert.equal(attempts.length,8);
  const pub=JSON.stringify(await cup.view(tid));for(const secret of ['12345678','sort_code','@example.test','payment_reference','payment_received','referee_token'])assert.ok(!pub.includes(secret),secret);
  const {createApiHandler}=await import('../server/api-handler.mjs');const req=(route,body)=>new Request('http://localhost/api/'+route,{method:body?'POST':'GET',headers:body?{origin:'http://localhost','content-type':'application/json'}:{},body:body?JSON.stringify(body):undefined});
  for(const role of ['organizer','admin']){const handler=createApiHandler({service,getUser:async()=>({...user,roles:[role]})});assert.equal((await handler(req('admin/team-cup?tournament='+tid))).status,200);}
  const handler=createApiHandler({service,getUser:async()=>null});for(const route of ['admin/email-diagnostic','admin/team-cup/edit-team','admin/team-cup/payment','admin/team-cup/operations'])assert.equal((await handler(req(route,{}))).status,401);
  assert.equal((await pool.query("select count(*)::integer as n from payment_email_outbox where cup_payment_id is not null and status='sent'")).rows[0].n,6);
});
test('admin metadata/roster/seed/groups/completed result overrides preserve authority and audit',async t=>{
  const {cup,tid,view}=await setup(t,fakeEmail);let s=await view();Object.assign(s.config,{capacity:18,fee_per_person:0,groupCount:2,qualifiers:1,team_size:4,start_time:'10:00',end_time:'17:00'});await cup.configure({tournamentId:tid,version:s.version,name:'Edited Cup',date:'2026-10-25',venue:'Edited hall',config:s.config},user);s=await view();assert.equal(s.name,'Edited Cup');assert.equal(s.config.time,'10:00–17:00');
  for(let n=1;n<=4;n++){const team=(await cup.register(input(tid,n))).team;await cup.teamStatus({tournamentId:tid,teamId:team.id,status:'confirmed',user});}
  s=await view();const t1=s.teams[0],members=[t1.members[1],t1.members[0],...t1.members.slice(2)].map(m=>({...m}));members[0].name='Corrected captain';await cup.editTeam({tournamentId:tid,version:s.version,teamId:t1.id,name:'Edited team',seed:1,members},user);s=await view();assert.equal(s.teams[0].members[0].name,'Corrected captain');assert.equal(s.seeds[t1.id],1);
  await cup.draw({tournamentId:tid,version:s.version});s=await view();let m=s.matches[0];const tie=s.ties.find(t=>t.id===m.tieId),lineup=Object.fromEntries(['a','b'].map(side=>[side,s.teams.find(t=>t.id===tie[side]).members.filter(p=>p.category==='men').map(p=>p.id)]));await cup.updateMatch({matchId:m.id,version:m.version,action:'setup',court:1,lineup},user);m=(await view()).matches.find(x=>x.id===m.id);await cup.updateMatch({matchId:m.id,version:m.version,action:'award',side:'a'},user);m=(await view()).matches.find(x=>x.id===m.id);
  await assert.rejects(cup.updateMatch({matchId:m.id,version:m.version,action:'reopen'},user),/Confirm/);await cup.updateMatch({matchId:m.id,version:m.version,action:'reopen',...override},user);m=(await view()).matches.find(x=>x.id===m.id);assert.equal(m.status,'pending');await cup.updateMatch({matchId:m.id,version:m.version,action:'result',games:[{a:21,b:15}],...override},user);assert.equal((await view()).matches.find(x=>x.id===m.id).winner,'a');
  s=await view();await cup.operations({tournamentId:tid,version:s.version,action:'winner',tieId:tie.id,teamId:tie.b,...override},user);assert.equal((await view()).ties.find(t=>t.id===tie.id).winner,tie.b);s=await view();await cup.operations({tournamentId:tid,version:s.version,action:'winner',tieId:tie.id,teamId:'',...override},user);assert.equal((await view()).ties.find(t=>t.id===tie.id).overrideWinner,undefined);
  s=await view();const g=s.groups.find(g=>!g.teams.includes(t1.id));await cup.operations({tournamentId:tid,version:s.version,action:'move-group',teamId:t1.id,groupId:g.id,...override},user);s=await view();assert.ok(s.groups.find(x=>x.id===g.id).teams.includes(t1.id));assert.equal(s.groups.flatMap(g=>g.teams).filter(id=>id===t1.id).length,1);
  await cup.resetDraw({tournamentId:tid,version:s.version,...override},user);s=await view();s.config.format='knockout';await cup.configure({tournamentId:tid,version:s.version,config:s.config},user);s=await view();await cup.draw({tournamentId:tid,version:s.version});s=await view();const final=s.ties.find(t=>t.round==='Final');await cup.operations({tournamentId:tid,version:s.version,action:'advance',tieId:final.id,teamId:t1.id,side:'a',...override},user);assert.equal((await view()).ties.find(t=>t.id===final.id).a,t1.id);
  const audit=await cup.auditView(null,tid);for(const action of ['settings_changed','roster_edited','reopen','result','winner','move-group','advance'])assert.ok(audit.events.some(e=>e.action===action),action);
});
test('email configuration diagnostics, provider rejection reason and redaction',async()=>{
  const {createEmailService,safeEmailReason}=await import('../server/email.mjs');const message={to:{email:'captain@example.test'},subject:'Test',html:'<p>Test</p>',text:'Test'};
  await assert.rejects(createEmailService({env:{}}).send(message,'key'),/API key is missing/);
  const env={EMAIL_API_KEY:'never-log-secret',EMAIL_FROM:'sender@example.test'};const adapter=createEmailService({env,fetchImpl:async()=>new Response(JSON.stringify({message:'Sender email has not been verified. never-log-secret 12345678'}),{status:400})});await assert.rejects(adapter.send(message,'key'),e=>e.httpStatus===400&&e.message.includes('not been verified')&&!e.message.includes('never-log-secret')&&!e.message.includes('12345678'));
  const verified=createEmailService({env,fetchImpl:async()=>new Response(JSON.stringify({senders:[{email:env.EMAIL_FROM,active:true}]}))});assert.equal((await verified.diagnose()).sender_verified,true);assert.ok(!JSON.stringify(await verified.diagnose()).includes(env.EMAIL_API_KEY));assert.ok(!safeEmailReason(new Error('bank 12-34-56 12345678')).includes('12-34-56'));
});
test('additive migration fixes only the old 2026 preset and preserves customized capacities/results',async t=>{
  const {PGlite}=await import('@electric-sql/pglite');const db=new PGlite();t.after(()=>db.close());const folder=path.join(__dirname,'../netlify/database/migrations');for(const name of fs.readdirSync(folder).filter(f=>f.endsWith('.sql')&&f<'202610030004').sort())await db.exec(fs.readFileSync(path.join(folder,name),'utf8'));
  for(const [id,capacity] of [['t_team_cup_2026',12],['t_custom',27]]){await db.query('insert into tournaments(id,name) values($1,$2)',[id,id]);await db.query('insert into team_cups(tournament_id,data) values($1,$2::jsonb)',[id,JSON.stringify({config:{capacity},groups:[{id:'preserved'}],ties:[{winner:'preserved'}]})]);}
  await db.exec(fs.readFileSync(path.join(folder,'202610030004_cup_admin_payments.sql'),'utf8'));const rows=(await db.query('select tournament_id,data from team_cups')).rows;assert.equal(rows.find(r=>r.tournament_id==='t_team_cup_2026').data.config.capacity,18);assert.equal(rows.find(r=>r.tournament_id==='t_custom').data.config.capacity,27);assert.equal(rows[0].data.ties[0].winner,'preserved');assert.equal((await db.query('select count(*)::integer as n from team_cup_payments')).rows[0].n,0);
});
test('configurable team size and forced correction reset started downstream matches and revoke their links',async t=>{
  const {cup,tid,view}=await setup(t,fakeEmail);let s=await view();Object.assign(s.config,{team_size:5,fee_per_person:0,groupCount:2,qualifiers:1});await cup.configure({tournamentId:tid,version:s.version,config:s.config},user);
  for(let n=1;n<=4;n++){const body=input(tid,n);body.members.push({name:`Reserve ${n}`,email:`reserve${n}@example.test`,phone:'07123456789',category:'men',shirtSize:'XL'});const team=(await cup.register(body)).team;await cup.teamStatus({tournamentId:tid,teamId:team.id,status:'confirmed',user});}
  assert.equal((await view()).teams[0].members.length,5);s=await view();await cup.draw({tournamentId:tid,version:s.version});s=await view();const groupMatch=s.matches[0];for(const m of s.matches)await cup.updateMatch({matchId:m.id,version:m.version,action:'award',side:'a'},user);
  s=await view();const final=s.ties.find(t=>t.round==='Final'),m=s.matches.find(m=>m.tieId===final.id&&m.discipline==='MD'),lineup=Object.fromEntries(['a','b'].map(side=>[side,s.teams.find(t=>t.id===final[side]).members.filter(p=>p.category==='men').slice(0,2).map(p=>p.id)]));await cup.updateMatch({matchId:m.id,version:m.version,action:'setup',court:1,lineup},user);const token=(await cup.token({matchId:m.id,action:'generate'},user)).token;let current=(await view()).matches.find(x=>x.id===m.id);await cup.updateMatch({matchId:m.id,version:current.version,action:'point',side:'a'},user);current=(await view()).matches.find(x=>x.id===groupMatch.id);
  await assert.rejects(cup.updateMatch({matchId:current.id,version:current.version,action:'award',side:'b'},user),/downstream/);await cup.updateMatch({matchId:current.id,version:current.version,action:'award',side:'b',...override},user);await assert.rejects(cup.referee(token),e=>e.status===403);assert.ok(!(await view()).matches.some(x=>x.id===m.id));
});
